-- ============================================
-- MIGRACIÓN 003: Seed de Parcelas
-- 73 parcelas de la Comunidad Viña Pelvin
-- ============================================

INSERT INTO parcelas (numero, direccion) VALUES
    ('1', 'Parcela 1, Viña Pelvin'),
    ('2', 'Parcela 2, Viña Pelvin'),
    ('3', 'Parcela 3, Viña Pelvin'),
    ('4', 'Parcela 4, Viña Pelvin'),
    ('5', 'Parcela 5, Viña Pelvin'),
    ('6', 'Parcela 6, Viña Pelvin'),
    ('7', 'Parcela 7, Viña Pelvin'),
    ('8', 'Parcela 8, Viña Pelvin'),
    ('9', 'Parcela 9, Viña Pelvin'),
    ('10', 'Parcela 10, Viña Pelvin'),
    ('11', 'Parcela 11, Viña Pelvin'),
    ('12', 'Parcela 12, Viña Pelvin'),
    ('13', 'Parcela 13, Viña Pelvin'),
    ('14', 'Parcela 14, Viña Pelvin'),
    ('15', 'Parcela 15, Viña Pelvin'),
    ('16', 'Parcela 16, Viña Pelvin'),
    ('17', 'Parcela 17, Viña Pelvin'),
    ('18', 'Parcela 18, Viña Pelvin'),
    ('19', 'Parcela 19, Viña Pelvin'),
    ('20', 'Parcela 20, Viña Pelvin'),
    ('21', 'Parcela 21, Viña Pelvin'),
    ('22', 'Parcela 22, Viña Pelvin'),
    ('23', 'Parcela 23, Viña Pelvin'),
    ('24', 'Parcela 24, Viña Pelvin'),
    ('25', 'Parcela 25, Viña Pelvin'),
    ('26', 'Parcela 26, Viña Pelvin'),
    ('27', 'Parcela 27, Viña Pelvin'),
    ('28', 'Parcela 28, Viña Pelvin'),
    ('29', 'Parcela 29, Viña Pelvin'),
    ('30', 'Parcela 30, Viña Pelvin'),
    ('31', 'Parcela 31, Viña Pelvin'),
    ('32', 'Parcela 32, Viña Pelvin'),
    ('33', 'Parcela 33, Viña Pelvin'),
    ('34', 'Parcela 34, Viña Pelvin'),
    ('35', 'Parcela 35, Viña Pelvin'),
    ('36', 'Parcela 36, Viña Pelvin'),
    ('37', 'Parcela 37, Viña Pelvin'),
    ('38', 'Parcela 38, Viña Pelvin'),
    ('39', 'Parcela 39, Viña Pelvin'),
    ('40', 'Parcela 40, Viña Pelvin'),
    ('41', 'Parcela 41, Viña Pelvin'),
    ('42', 'Parcela 42, Viña Pelvin'),
    ('43', 'Parcela 43, Viña Pelvin'),
    ('44', 'Parcela 44, Viña Pelvin'),
    ('45', 'Parcela 45, Viña Pelvin'),
    ('46', 'Parcela 46, Viña Pelvin'),
    ('47', 'Parcela 47, Viña Pelvin'),
    ('48', 'Parcela 48, Viña Pelvin'),
    ('49', 'Parcela 49, Viña Pelvin'),
    ('50', 'Parcela 50, Viña Pelvin'),
    ('51', 'Parcela 51, Viña Pelvin'),
    ('52', 'Parcela 52, Viña Pelvin'),
    ('53', 'Parcela 53, Viña Pelvin'),
    ('54', 'Parcela 54, Viña Pelvin'),
    ('55', 'Parcela 55, Viña Pelvin'),
    ('56', 'Parcela 56, Viña Pelvin'),
    ('57', 'Parcela 57, Viña Pelvin'),
    ('58', 'Parcela 58, Viña Pelvin'),
    ('59', 'Parcela 59, Viña Pelvin'),
    ('60', 'Parcela 60, Viña Pelvin'),
    ('61', 'Parcela 61, Viña Pelvin'),
    ('62', 'Parcela 62, Viña Pelvin'),
    ('63', 'Parcela 63, Viña Pelvin'),
    ('64', 'Parcela 64, Viña Pelvin'),
    ('65', 'Parcela 65, Viña Pelvin'),
    ('66', 'Parcela 66, Viña Pelvin'),
    ('67', 'Parcela 67, Viña Pelvin'),
    ('68', 'Parcela 68, Viña Pelvin'),
    ('69', 'Parcela 69, Viña Pelvin'),
    ('70', 'Parcela 70, Viña Pelvin'),
    ('71', 'Parcela 71, Viña Pelvin'),
    ('72', 'Parcela 72, Viña Pelvin'),
    ('73', 'Parcela 73, Viña Pelvin');

-- Usuario administrador por defecto (contraseña: admin123 - CAMBIAR EN PRODUCCIÓN)
-- Hash generado con bcrypt cost 10
INSERT INTO users (email, password_hash, name, role, email_verified) VALUES
    ('admin@vinapelvin.cl', '$2a$10$N9qo8uLOickgx2ZMRZoMy.MqrqbKjE1QVLLqWqJxJjJxJjJxJjJxJ', 'Administrador', 'directiva', TRUE);
